// Code generated by zederr generator. DO NOT EDIT.
package zederrtest
//
// import (
// 	pkgzederr "github.com/amanbolat/zederr/pkg/stderr"
// 	pkgcodes "google.golang.org/grpc/codes"
// 	pkgstructpb "google.golang.org/protobuf/types/known/structpb"
// )
//
// // CoreErrorParams is the parameters for CoreError error.
// type CoreErrorParams struct {
// 	Error string
// 	User  string
// }
//
// // ErrorParams returns CoreErrorParams as a map.
// func (p CoreErrorParams) ErrorParams() map[string]interface{} {
// 	return map[string]interface{}{
// 		"Error": p.Error,
// 		"User":  p.User,
// 	}
// }
//
// // ProtoParams returns CoreErrorParams as a protobuf struct.
// func (p CoreErrorParams) ProtoParams() *pkgstructpb.Struct {
// 	st, _ := pkgstructpb.NewStruct(p.ErrorParams())
//
// 	return st
// }
//
// // NewCoreError creates a new CoreError.
// // Description: core error
// func NewCoreError(err error, paramError string, user string) *pkgzederr.Error {
// 	return pkgzederr.NewError(err, "core.error", 400, pkgcodes.Unknown, CoreErrorParams{
// 		Error: paramError,
// 		User:  user,
// 	})
// }
