// Code generated by zederr generator. DO NOT EDIT.
package zederr

import (
	context "context"
	zeerr "github.com/amanbolat/zederr/zeerr"
	zei18n "github.com/amanbolat/zederr/zei18n"
	pkgcodes "google.golang.org/grpc/codes"
	time "time"
)

var defaultLocale = "en"

var localizer = func() zeerr.Localizer {
	l, err := zei18n.NewLocalizer(defaultLocale, ErrorMessages())
	if err != nil {
		panic(err)
	}

	return l
}()

// NewAccountLocked creates a new `account_locked` error.
//
// Description: Account is locked due to too many failed login attempts.
func NewAccountLocked(ctx context.Context, user_id string, failed_attempts int, unlock_time time.Time) *zeerr.Error {
	return zeerr.NewError(
		ctx,
		localizer,
		"account_locked",
		401,
		pkgcodes.Canceled,
		map[string]any{
			"user_id":         user_id,
			"failed_attempts": failed_attempts,
			"unlock_time":     unlock_time,
		},
	)
}
