builds:
  - binary: zederr
    main: ./cmd
    flags:
      - -trimpath
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
        - amd64
        - arm64

universal_binaries:
  - id: zederr
    name_template: "{{.ProjectName}}_{{.Version}}"
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"

brews:
  - name: zederr
    homepage: "https://github.com/amanbolat/zederr"
    license: "Apache-2.0"
    description: > 
      A tool for error codes documentation and code generation. 
      You can define all the errors in one YAML file and generate strictly typed error constructors. 
      Error public messages are automatically localized on initialization based on the user locale.
    tap:
      owner: amanbolat
      name: homebrew-amanbolat
    commit_author:
      name: amanbolat
      email: amanbolat@me.com
    install: |
      bin.install zederr

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
