project_name: zederr
version: 2

builds:
  - binary: zederr
    main: ./cmd/
    flags:
      - -trimpath
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

brews:
  - name: zederr
    folder: Formula
    homepage: "https://github.com/amanbolat/zederr"
    license: "Apache-2.0"
    description: >
      A tool for error codes documentation and code generation. 
      You can define all the errors in one YAML file and generate strictly typed error constructors. 
      Error public messages are automatically localized on initialization based on the user locale.
    tap:
      owner: amanbolat
      name: homebrew-amanbolat
    commit_author:
      name: amanbolat
      email: amanbolat@me.com
    install: |
      bin.install zederr

