["acme.com/auth/AccountLocked_argument_failed_attempts"]
other = "Number of failed login attempts"

["acme.com/auth/AccountLocked_argument_unlock_time"]
other = "Time when the account will be unlocked"

["acme.com/auth/AccountLocked_argument_user_id"]
other = "User ID"

["acme.com/auth/AccountLocked_deprecated"]
other = ""

["acme.com/auth/AccountLocked_description"]
other = "Account is locked due to too many failed login attempts."

["acme.com/auth/AccountLocked_internal_msg"]
other = "User with id {{ .user_id }} failed to provide correct credentials {{ .failed_attempts }} times. The account is locked until {{ .unlock_time }}."

["acme.com/auth/AccountLocked_public_msg"]
other = "Your account is locked due to too many failed login attempts ({{ .failed_attempts }})."

["acme.com/auth/AccountLocked_title"]
other = "Account is locked"
