// Code generated by zederr generator. DO NOT EDIT.
package zederrtest

import (
	context "context"
	template "html/template"

	zeerr "github.com/amanbolat/zederr/zeerr"
	zei18n "github.com/amanbolat/zederr/zei18n"
	pkgcodes "google.golang.org/grpc/codes"
)

var defaultLocale = "en"

var localizer = func() zeerr.Localizer {
	l, err := zei18n.NewLocalizer(defaultLocale, ErrorMessages())
	if err != nil {
		panic(err)
	}

	return l
}()

var codeInternalMsgTmpl = func() *template.Template {
	t, _ := template.New("").Parse("internal message {{ .arg_1 }}")
	return t
}()

// NewCode creates a new Code.
//
// Description: description
func NewCode(ctx context.Context, arg_1 string) error {
	return zeerr.NewError(
		ctx,
		localizer,
		"Code",
		"acme.com",
		"ns",
		400,
		pkgcodes.Canceled,
		codeInternalMsgTmpl,
		zeerr.Arguments{
			"arg_1": arg_1,
		},
	)
}
