name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - uses: sigstore/cosign-installer@v3.3.0
      - uses: anchore/sbom-action/download-syft@v0.15.9

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@696b757ee8f3742e68b261173b9eeeb96306a57f # v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
